com.ejemplos.devices.qr.dialog ios

diff --git a/.github/workflows/cd-ios-qr.Ejemplo_LectorQR_Dialog.yml b/.github/workflows/cd-ios-qr.Ejemplo_LectorQR_Dialog.yml
--- a/.github/workflows/cd-ios-qr.Ejemplo_LectorQR_Dialog.yml
+++ b/.github/workflows/cd-ios-qr.Ejemplo_LectorQR_Dialog.yml
@@ -2,19 +2,21 @@
 
 on:
   
-  # push:
-  #   branches: 
-  #     - main
+  push:
+    branches: 
+      - main
 
-  #   paths:
-  #     - 'Ejemplos_Devices/QR/Ejemplo_LectorQR_Dialog/**'
-  #     - '!**.md'
-  #     - '!**/*.gitignore'
-  #     - '!**/*.gitattributes'
+    paths:
+      - 'APPGDA/**'
+      - '!**.md'
+      - '!**/*.gitignore'
+      - '!**/*.gitattributes'
 
   workflow_call:
 
 env:
+  PIPELINE_VERSION: '202606261239_ejemplos'
+
   #XCODE_VERSION: '26.3'  
   #XCODE_VERSION_SHORT: '26.3'
   #XCODE_FILE_INSTALLER: 'Xcode_26_Universal.xip'
@@ -30,7 +32,7 @@ env:
   DOTNET_TARGET_VERSION: 'net10.0'
   DOTNET_VERSION_WORKLOAD: '10.0.100'
 
-  # ─── Datos específicos del proyecto GPS ────────────────────────────────────── 
+  # ─── Datos específicos del proyecto ───────────────────────────────────────── 
   PACKAGE_NAME: 'com.ejemplos.devices.qr.dialog'
   SOLUTION_FOLDER: 'Ejemplos_Devices'
   PROJECTS_ROOT: 'QR' 
@@ -38,7 +40,7 @@ env:
   PROJECT_NAME: 'Ejemplo_LectorQR_Dialog'
   PROJECT_FILE: 'Ejemplo_LectorQR_Dialog.csproj'
   # ─────────────────────────────────────────────────────────────────────────────
-
+  
   RUNTIME_IDENTIFIER_SIMULATOR: 'iossimulator-arm64' 
   BUILD_CONFIG_SIMULATOR: 'Release'
   DEVICE_SIMULATOR: 'iPhone 17 Pro Max'
@@ -59,6 +61,8 @@ jobs:
         echo "Model hardware: $(sysctl -n hw.model)"
         echo "Cores numbers: $(sysctl -n hw.ncpu)"
 
+    # Clone repository
+
     - name: Checkout the code
       uses: actions/checkout@v4
       with:
@@ -78,6 +82,7 @@ jobs:
         # /Users/runner/work/Ejemplos_Maui_Devices/Ejemplos_Maui_Devices/Ejemplos_Devices/QR/Ejemplo_LectorQR_Dialog:
         #  Ejemplo_LectorQR_Dialog.csproj
         #  ...
+
 
     # XCODE
 
@@ -230,12 +235,26 @@ jobs:
 
         PLIST_PATH=$SOLUTION_PATH/${{ env.PROJECTS_ROOT }}/${{ env.PROJECT_NAME}}/Platforms/iOS/Info.plist
         PLIST_PATH=$(realpath "$PLIST_PATH")
-        
+                
         echo "PROJECT_PATH=$PROJECT_PATH" >> $GITHUB_ENV
         echo "SOLUTION_PATH=$SOLUTION_PATH" >> $GITHUB_ENV
         echo "PLIST_PATH=$PLIST_PATH" >> $GITHUB_ENV
 
         echo "Recursive path: $(ls -lshR $SOLUTION_PATH)"
+
+    # CPY. COPIANDO RECURSOS A LA APLICACION
+
+    - name: CPY. Ejecuta el script para copiar los recursos
+      run: |
+        cd ${{ github.workspace }}
+        echo "Directorio de trabajo (workspace): $(pwd)"
+        # /Users/runner/work/GDA.APP/GDA.APP
+        echo "Ficheros: $(ls -l)"
+        # /Users/runner/work/GDA.APP/GDA.APP
+
+        ls ./Recursos
+        chmod +x ./Utils/copiarRecursos.sh
+        bash ./Utils/copiarRecursos.sh
 
     # VERSIONADO BUNDLE
 
@@ -263,7 +282,7 @@ jobs:
     - name: MANIFEST. Validar manifests iOS
       run: |
         echo "Validando plists"
-        plutil -lint "${{ env.PROJECT_PATH }}/Platforms/iOS/Info.plist" || { echo "ERROR: Info.plist inválido"; exit 1; }      
+        plutil -lint "${{ env.PLIST_PATH }}" || { echo "ERROR: Info.plist inválido"; exit 1; }      
         echo "Todos los plists válidos"
        
     # BUILD SIMULADOR
@@ -275,14 +294,6 @@ jobs:
         #dotnet clean "${{ env.PROJECT_FOLDER }}/${{ env.PROJECT_FILE }}" -f ${{ env.DOTNET_TARGET_VERSION }}-ios
         dotnet clean "${{ env.PROJECTS_ROOT }}/${{ env.PROJECT_NAME}}/${{ env.PROJECT_FILE }}" -f ${{ env.DOTNET_TARGET_VERSION }}-ios
         # dotnet clean Ejemplo_LectorQR_Dialog.csproj -f net10.0-ios
-
-    # - name: PRE-BUILD. Generar ApiKeys.cs desde secreto
-    #   run: |
-    #     APIKEYS_PATH=${{ env.PROJECT_PATH }}/Services/ApiKeys.cs
-    #     cat "$APIKEYS_PATH.template" \
-    #       | sed 's/REEMPLAZAR_CON_TU_API_KEY/${{ secrets.GOOGLE_MAPS_API_KEY }}/' \
-    #       > "$APIKEYS_PATH"
-    #     echo "ApiKeys.cs generado en: $APIKEYS_PATH"
 
     - name: BUILD SIMULADOR. Restaurar dependencias
       run: |
@@ -317,12 +328,10 @@ jobs:
             -v normal
 
         echo "Imprime la carpeta bin recursiva:"
-        #ls -Rl "${{ env.PROJECT_FOLDER }}/bin/"
         ls -Rl "${{ env.PROJECTS_ROOT }}/${{ env.PROJECT_NAME }}/bin/"
-        
-        
+                
         BASE_PATH=${{ env.PROJECT_PATH }}/bin/${{ env.BUILD_CONFIG_SIMULATOR }}/${{ env.DOTNET_TARGET_VERSION }}-ios/${{ env.RUNTIME_IDENTIFIER_SIMULATOR }}
-        #APP_PATH=${BASE_PATH}/${{ env.PROJECT_FOLDER }}.app
+        BASE_PATH=$(realpath "$BASE_PATH") 
         APP_PATH=${BASE_PATH}/${{ env.PROJECT_NAME }}.app
         APP_PATH=$(realpath "$APP_PATH")
 
@@ -352,14 +361,12 @@ jobs:
         echo "Limpiando firmas previas y atributos corruptos..."
         xattr -cr "${{ env.APP_PATH }}"
         rm -rf "${{ env.APP_PATH }}/_CodeSignature"
-        #chmod +x "${{ env.APP_PATH }}/${{ env.PROJECT_FOLDER }}"
         chmod +x "${{ env.APP_PATH }}/${{ env.PROJECT_NAME }}"
 
         echo "Firmando contenido interno (DLLs y AOT) uno por uno..."
         find "${{ env.APP_PATH }}" -name "*.dll" -or -name "*.dylib" -or -name "*.aotdata*" | xargs codesign --force --sign "-" --timestamp=none
         
         echo "Firmando el binario principal con los Entitlements..."
-        #codesign --force --sign "-" --timestamp=none --entitlements "$ENTITLEMENTS_PATH" "${{ env.APP_PATH }}/${{ env.PROJECT_FOLDER }}"
         codesign --force --sign "-" --timestamp=none --entitlements "$ENTITLEMENTS_PATH" "${{ env.APP_PATH }}/${{ env.PROJECT_NAME }}"
         
         echo "Sellado final del paquete (Bundle)..."
@@ -372,11 +379,8 @@ jobs:
 
     - name: BUILD SIMULADOR. Test entitlements
       run: |  
-        #file "${{ env.APP_PATH }}/${{ env.PROJECT_FOLDER }}"
         file "${{ env.APP_PATH }}/${{ env.PROJECT_NAME }}"
-
         /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" "${{ env.APP_PATH }}/Info.plist"
-        #codesign -d --entitlements :- "${{ env.APP_PATH }}/${{ env.PROJECT_FOLDER }}"
         codesign -d --entitlements :- "${{ env.APP_PATH }}/${{ env.PROJECT_NAME }}"
         
     # PUBLISH SIMULADOR
@@ -415,8 +419,8 @@ jobs:
         echo "Esperando algo como (Signature=adhoc): "
         codesign -vvv --display "${APP_PATH}"
         cd "${{ github.workspace }}"
-        chmod ugo+rwx ./Utilities/simular.sh
-        ./Utilities/simular.sh
+        chmod ugo+rwx ./Utils/simular.sh
+        ./Utils/simular.sh
 
     - name: RELEASE SIMULADOR. Subir GIF de evidencia  
       uses: actions/upload-artifact@v4
@@ -431,8 +435,11 @@ jobs:
           /tmp/app_stderr.txt
         if-no-files-found: warn
         retention-days: 1
-
+            
     - name: Clean up keychain and provisioning profile
       if: ${{ always() }}
       run: |
-        echo "Limpieza de keychain y perfiles de aprovisionamiento"
+        if test -f "$RUNNER_TEMP/app-signing.keychain-db"; then
+          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
+        fi
+        rm -f ~/Library/MobileDevice/Provisioning\ Profiles/${{ env.PROJECT_NAME }}.mobileprovision
